<a href="https://colab.research.google.com/github/DeanAdrian/AIDA3-Laboratory/blob/main/58026_PrExam_Jabolt/58026_PrExam_Jabolt.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

## 1. Perceptron Algorithm

In [2]:
def activation(y):
  if y > 0:
    y = 1
  elif y <= 0:
    y = 0
  return y

def perceptronAlgo(x):
  W = np.array([-1, -1])
  b = 1
  y = np.dot(W, x) + b
  y = activation(y)
  return y

The functions above contain the activation function as well as the perceptron algorithm function. The activation function will return either a 1 or 0 value for y depending on its value after being computed for in the perceptron algorithm function.

### Output

In [3]:
input1 = np.array([0, 0])
input2 = np.array([0, 1])
input3 = np.array([1, 0])
input4 = np.array([1, 1])

In [4]:
print("NOR 0 0 =", perceptronAlgo(input1))

NOR 0 0 = 1


In [5]:
print("NOR 0 1 =", perceptronAlgo(input2))

NOR 0 1 = 0


In [6]:
print("NOR 1 0 =", perceptronAlgo(input3))

NOR 1 0 = 0


In [7]:
print("NOR 1 1 =", perceptronAlgo(input4))

NOR 1 1 = 0


## 2. Declaration of the Features and Targets of the Model

In [8]:
w1 = np.array([[1, -1],
               [-1, 1]])
w2 = np.array([[1, 2],
               [2, 1]])
w3 = np.array([-1, 1])
x = np.array([1, 0])

For the above requirement, the needed features and weights were declared as array variables to be called by used as inputs for the functions in the later part of this notebook.

### Output

In [9]:
w1

array([[ 1, -1],
       [-1,  1]])

In [10]:
w2

array([[1, 2],
       [2, 1]])

In [11]:
w3

array([-1,  1])

In [12]:
x

array([1, 0])

## 3. Forward Propagation

In [13]:
def forwardProp(x, w1, w2, w3): 
  z1 = np.dot(x, w1)
  a1 = np.tanh(z1)
  z2 = np.dot(a1, w2)
  a2 = np.tanh(z2)
  z3 = np.dot(a2, w3)
  a3 = np.tanh(z3)
  return a1, a2, a3

The forward propagation function uses all of the features and weights created in the number above as its inputs. The function alternates between the use of np.dot to get the dot product of two inputs and np.tanh which is the activation function. The function then outputs three variables created in the function as a tuple, and will be used again in the next function.

### Output

In [14]:
forwardProp(x, w1, w2, w3)[2]

0.8575549394724464

## 4. Back Propagation

In [15]:
def backwardProp(x, w1, w2, w3):
  y   = forwardProp(x, w1, w2, w3)[0]
  y1  = forwardProp(x, w1, w2, w3)[1]
  y2  = forwardProp(x, w1, w2, w3)[2]
  y3  = np.tanh(y2)
  dn  = 2.86
  err = dn - y3
  lr  = 0.25

  dv = (1 - y3) * (1 + y3)
  delta = err * dv
  W_1 = w3 - (lr * delta) * y2

  dv1 = (1 - y2) * (1 + y2)
  delta1 = (w2 * dv1) * delta
  W_2 = w2 - (lr * delta) * delta1

  dv2 = (1 - y1) * (1 + y1)
  delta2 = (w1 * dv2) * delta1
  W_3 = w1 - (lr * delta2) * y

  return W_1, W_2, W_3

Above is the backward propagation function, it uses the same inputs as the forward propagation function. In the first part of the function the outputs of the forward propagation function are set as individual variables to be used in the computation part of the code. The values of the other variables are taken from the given problem for this activity.

The way the function calculates all of the new wights in similar steps. The back propagation function also returns the three variable as a tuple.

### Output

In [16]:
backwardProp(x, w1, w2, w3)[2]

array([[ 0.96685425, -1.0662915 ],
       [-0.9337085 ,  1.03314575]])

## 5.  Updated Weights

In [17]:
def updatedWeights():
  for i in range(0, 3):
    print(f"Updated Weight {i+1}:",backwardProp(x, w1, w2, w3)[i], "\n")

The updated weights function simply uses the backward propagation function, and outputs each index in the tuple separately.

### Output

In [18]:
updatedWeights()

Updated Weight 1: [-1.23995798  0.76004202] 

Updated Weight 2: [[0.91713034 1.83426069]
 [1.83426069 0.91713034]] 

Updated Weight 3: [[ 0.96685425 -1.0662915 ]
 [-0.9337085   1.03314575]] 

