<a href="https://colab.research.google.com/github/DeanAdrian/AIDA3-Laboratory/blob/main/58026_PrExam_Jabolt/58026_PrExam_Jabolt.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

## 1. Perceptron Algorithm

In [2]:
def perceptronAlgo(input1, input2):
  if(input1 == 0) and (input1 == 0):
    return 1
  elif(input1 == 0) and (input2 == 1):
    return 0
  elif(input1 == 1) and (input2 == 0):
    return 0
  elif(input1 == 1) and (input2 == 1):
    return 0

### Output

In [3]:
print("NOR 0 0 =", perceptronAlgo(0,0))

NOR 0 0 = 1


In [4]:
print("NOR 0 1 =", perceptronAlgo(0,1))

NOR 0 1 = 1


In [5]:
print("NOR 1 0 =", perceptronAlgo(1,0))

NOR 1 0 = 0


In [6]:
print("NOR 1 1 =", perceptronAlgo(1,1))

NOR 1 1 = 0


## 2. Declaration of the Features and Targets of the Model

In [7]:
w1 = np.array([[1, -1],
               [-1, 1]])
w2 = np.array([[1, 2],
               [2, 1]])
w3 = np.array([-1, 1])
x = np.array([1, 0])

### Output

In [8]:
w1

array([[ 1, -1],
       [-1,  1]])

In [9]:
w2

array([[1, 2],
       [2, 1]])

In [10]:
w3

array([-1,  1])

In [11]:
x

array([1, 0])

## 3. Forward Propagation

In [12]:
def forwardProp(x, w1, w2, w3): 
  z1 = np.dot(x, w1)
  a1 = np.tanh(z1)
  z2 = np.dot(a1, w2)
  a2 = np.tanh(z2)
  z3 = np.dot(a2, w3)
  a3 = np.tanh(z3)
  return a1, a2, a3

### Output

In [13]:
forwardProp(x, w1, w2, w3)[2]

0.8575549394724464

## 4. Back Propagation

In [14]:
def backwardProp(x, w1, w2, w3):
  y   = forwardProp(x, w1, w2, w3)[0]
  y1  = forwardProp(x, w1, w2, w3)[1]
  y2  = forwardProp(x, w1, w2, w3)[2]
  y3  = np.tanh(y2)
  dn  = 2.86
  err = dn - y3
  lr  = 0.25

  dv = (1 - y3) * (1 + y3)
  delta = err * dv
  W_1 = w3 - (lr * delta) * y2

  dv1 = (1 - y2) * (1 + y2)
  delta1 = (w2 * dv1) * delta
  W_2 = w2 - (lr * delta) * delta1

  dv2 = (1 - y1) * (1 + y1)
  delta2 = (w1 * dv2) * delta1
  W_3 = w1 - (lr * delta2) * y

  return W_1, W_2, W_3

### Output

In [15]:
backwardProp(x, w1, w2, w3)[2]

array([[ 0.96685425, -1.0662915 ],
       [-0.9337085 ,  1.03314575]])

## 5.  Updated Weights

In [16]:
def updatedWeights():
  for i in range(0, 3):
    print(f"Updated Weight {i+1}:",backwardProp(x, w1, w2, w3)[i], "\n")

### Output

In [17]:
updatedWeights()

Updated Weight 1: [-1.23995798  0.76004202] 

Updated Weight 2: [[0.91713034 1.83426069]
 [1.83426069 0.91713034]] 

Updated Weight 3: [[ 0.96685425 -1.0662915 ]
 [-0.9337085   1.03314575]] 

